param(
    [Parameter(Mandatory = $true)]
    [string]$OutputFile,
    [string]$ReleaseTag = "",
    [string]$VersionInfoSuffix = "",
    [string]$UpdateRepository = ""
)

$ErrorActionPreference = 'Stop'

function ConvertTo-GitHubRepositorySlug {
    param([string]$Value)

    if ([string]::IsNullOrWhiteSpace($Value)) {
        return ""
    }

    $candidate = $Value.Trim().TrimEnd('/')
    if ($candidate.EndsWith('.git', [StringComparison]::OrdinalIgnoreCase)) {
        $candidate = $candidate.Substring(0, $candidate.Length - 4)
    }

    if ($candidate -match '^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$') {
        return $candidate
    }

    if ($candidate -match '^https?://(?:[^/]+@)?github\.com/([^/]+)/([^/]+)$') {
        return "$($Matches[1])/$($Matches[2])"
    }

    if ($candidate -match '^git@github\.com:([^/]+)/([^/]+)$') {
        return "$($Matches[1])/$($Matches[2])"
    }

    if ($candidate -match '^ssh://git@github\.com/([^/]+)/([^/]+)$') {
        return "$($Matches[1])/$($Matches[2])"
    }

    return ""
}

function Resolve-UpdateRepository {
    $sources = @(
        $UpdateRepository,
        $env:GITHUB_REPOSITORY
    )

    foreach ($source in $sources) {
        $slug = ConvertTo-GitHubRepositorySlug $source
        if (-not [string]::IsNullOrWhiteSpace($slug)) {
            return $slug
        }
    }

    try {
        $originUrl = (git remote get-url origin 2>$null).Trim()
        $slug = ConvertTo-GitHubRepositorySlug $originUrl
        if (-not [string]::IsNullOrWhiteSpace($slug)) {
            return $slug
        }
    }
    catch {
        # Ignore non-git source archives or environments without git.
    }

    return "xxxxuanran/N_m3u8DL-RE"
}

if ([string]::IsNullOrWhiteSpace($VersionInfoSuffix)) {
    $suffixScript = Join-Path $PSScriptRoot 'Get-VersionInfoSuffix.ps1'
    $VersionInfoSuffix = (& $suffixScript -ReleaseTag $ReleaseTag).Trim()
}

$UpdateRepository = Resolve-UpdateRepository
$versionInfo = "N_m3u8DL-RE (Beta version) $VersionInfoSuffix"
$escaped = $versionInfo.Replace('\', '\\').Replace('"', '\"')
$escapedSuffix = $VersionInfoSuffix.Replace('\', '\\').Replace('"', '\"')
$escapedUpdateRepository = $UpdateRepository.Replace('\', '\\').Replace('"', '\"')

$content = @"
// <auto-generated />
using System.Reflection;

[assembly: AssemblyInformationalVersion("$escapedSuffix")]

namespace N_m3u8DL_RE.CommandLine;

internal static partial class CommandInvoker
{
    public const string VERSION_INFO = "$escaped";
    public const string UPDATE_REPOSITORY = "$escapedUpdateRepository";
}
"@

$directory = Split-Path -Parent $OutputFile
if (-not [string]::IsNullOrWhiteSpace($directory)) {
    New-Item -ItemType Directory -Force -Path $directory | Out-Null
}

Set-Content -Path $OutputFile -Value $content -Encoding utf8NoBOM
