#!/usr/bin/env sh
set -eu

OUTPUT_FILE=""
RELEASE_TAG=""
VERSION_INFO_SUFFIX=""

while [ $# -gt 0 ]; do
  case "$1" in
    -OutputFile) OUTPUT_FILE="$2"; shift 2 ;;
    -ReleaseTag) RELEASE_TAG="$2"; shift 2 ;;
    -VersionInfoSuffix) VERSION_INFO_SUFFIX="$2"; shift 2 ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

if [ -z "$OUTPUT_FILE" ]; then
  echo "OutputFile is required" >&2
  exit 1
fi

if [ -z "$VERSION_INFO_SUFFIX" ]; then
  SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
  VERSION_INFO_SUFFIX=$(sh "$SCRIPT_DIR/Get-VersionInfoSuffix.sh" -ReleaseTag "$RELEASE_TAG")
fi

version_info="N_m3u8DL-RE (Beta version) $VERSION_INFO_SUFFIX"
escaped=$(printf '%s' "$version_info" | sed 's/\\/\\\\/g; s/"/\\"/g')
escaped_suffix=$(printf '%s' "$VERSION_INFO_SUFFIX" | sed 's/\\/\\\\/g; s/"/\\"/g')

mkdir -p "$(dirname "$OUTPUT_FILE")"
cat > "$OUTPUT_FILE" <<EOF
// <auto-generated />
using System.Reflection;

[assembly: AssemblyInformationalVersion("$escaped_suffix")]

namespace N_m3u8DL_RE.CommandLine;

internal static partial class CommandInvoker
{
    public const string VERSION_INFO = "$escaped";
}
EOF
