param(
    [Parameter(Mandatory = $true)]
    [string]$OutputFile,
    [string]$ReleaseTag = "",
    [string]$VersionInfoSuffix = ""
)

$ErrorActionPreference = 'Stop'

if ([string]::IsNullOrWhiteSpace($VersionInfoSuffix)) {
    $suffixScript = Join-Path $PSScriptRoot 'Get-VersionInfoSuffix.ps1'
    $VersionInfoSuffix = (& $suffixScript -ReleaseTag $ReleaseTag).Trim()
}

$versionInfo = "N_m3u8DL-RE (Beta version) $VersionInfoSuffix"
$escaped = $versionInfo.Replace('\', '\\').Replace('"', '\"')

$content = @"
// <auto-generated />
namespace N_m3u8DL_RE.CommandLine;

internal static partial class CommandInvoker
{
    public const string VERSION_INFO = "$escaped";
}
"@

$directory = Split-Path -Parent $OutputFile
if (-not [string]::IsNullOrWhiteSpace($directory)) {
    New-Item -ItemType Directory -Force -Path $directory | Out-Null
}

Set-Content -Path $OutputFile -Value $content -Encoding utf8NoBOM
